// src/constants/questions.js

export const JUNIOR_QUESTIONS = [
  "JVM의 구조와 동작 원리를 설명하세요.",
  "JPA의 영속성 컨텍스트란 무엇인가?",
  "@Transactional의 동작 원리를 설명하세요.",
  "Spring Boot와 Spring Framework의 차이점은?",
  "REST API란 무엇인가?",
  "HTTP 상태코드 종류와 의미를 설명하세요.",
  "DI와 IoC의 차이점은?",
  "싱글톤 패턴의 문제점은?",
  "Thread와 Process의 차이점은?",
  "Garbage Collection이란?",
  "HashMap의 내부 구조는?",
  "equals와 hashCode의 관계는?",
  "List와 Set의 차이점은?",
  "ArrayList와 LinkedList 차이점은?",
  "TCP와 UDP 차이점은?",
  "OSI 7계층을 설명하세요.",
  "데이터베이스 인덱스란?",
  "정규화란 무엇인가?",
  "트랜잭션의 ACID는?",
  "Deadlock이란?",
  "Spring Security란?",
  "JWT 인증 방식은?",
  "세션과 쿠키 차이점은?",
  "CORS란 무엇인가?",
  "N+1 문제란?",
  "Fetch Join이란?",
  "Gradle과 Maven 차이점은?",
  "Docker란 무엇인가?",
  "Kubernetes란?",
  "CI/CD란?",
  "Git rebase와 merge 차이점은?",
  "객체지향 4대 원칙은?",
  "인터페이스와 추상클래스 차이점은?",
  "Functional Interface란?",
  "Stream API란?",
  "람다 표현식이란?",
  "Spring MVC 동작 원리?",
  "DispatcherServlet 역할은?",
  "Filter와 Interceptor 차이점은?",
  "ORM이란?",
  "CAP 이론이란?",
  "MSA란?",
  "Redis를 사용하는 이유는?",
  "비동기와 동기 차이점은?",
  "Blocking과 Non-blocking 차이?",
  "Thread Pool이란?",
  "GC 튜닝이란?",
  "JPA flush 동작은?",
  "DTO와 Entity 분리 이유는?",
  "예외 처리 전략은?"
];
